# Generated by Django 6.0.3 on 2026-04-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text="Profile photo — 'Click camera icon to change photo'", null=True, upload_to='profile_images/'),
        ),
    ]
