# Generated by Django 6.0.3 on 2026-04-25 00:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_invoice_id', models.CharField(help_text="Stripe invoice ID, e.g. 'in_1ABC...'. Displayed as INV-2024-003 on screen.", max_length=120, unique=True)),
                ('amount_cents', models.PositiveIntegerField(help_text='Amount in cents — e.g. 999 = $9.99, 2870 = $28.70')),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('invoice_date', models.DateField()),
                ('invoice_pdf_url', models.URLField(blank=True, default='', help_text='Stripe invoice PDF download URL.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('free_trial', 'Free Trial'), ('professional', 'Professional')], db_index=True, default='free_trial', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='trial', max_length=15)),
                ('trial_start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Trial start time. Expires in 5 days.')),
                ('trial_end_date', models.DateTimeField(blank=True, help_text='trial_start_date + 5 days — auto-set on save.', null=True)),
                ('pro_start_date', models.DateTimeField(blank=True, null=True)),
                ('pro_end_date', models.DateTimeField(blank=True, help_text='Stripe subscription period end date.', null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
    ]
