# Generated by Django 6.0.3 on 2026-05-09 01:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='pro_start_date',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount_cents',
            field=models.PositiveIntegerField(help_text='Amount in cents (e.g., 999 for $9.99)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_pdf_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('failed', 'Failed')], default='paid', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='stripe_invoice_id',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan_type',
            field=models.CharField(choices=[('free_trial', 'Free Trial'), ('professional', 'Professional')], default='free_trial', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='pro_end_date',
            field=models.DateTimeField(blank=True, help_text='End date of the paid professional plan.', null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='trial', max_length=15),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, help_text='Calculated trial expiration date.', null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='trial_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date when the 5-day trial began.'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(help_text='The user associated with this subscription.', on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
