# Generated by Django 6.0.3 on 2026-05-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_subscription_options_remove_invoice_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='amount_cents',
            field=models.PositiveIntegerField(help_text='Amount in cents'),
        ),
    ]
