# Generated by Django 6.0.3 on 2026-06-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_invoice_amount_cents'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='revenuecat_app_user_id',
            field=models.CharField(blank=True, help_text='RevenueCat app_user_id (= Django user.pk হিসেবে set করা)', max_length=120, null=True),
        ),
    ]
