# Generated by Django 6.0.3 on 2026-04-06 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('subject', models.CharField(blank=True, default='', max_length=100)),
                ('grade_level', models.CharField(blank=True, default='', max_length=50)),
                ('school', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_notes', models.TextField(help_text='Rough notes during walkthrough.')),
                ('rating', models.CharField(choices=[('distinguished', 'Distinguished'), ('accomplished', 'Accomplished'), ('proficient', 'Proficient'), ('developing', 'Developing'), ('improvement_needed', 'Improvement Needed')], db_index=True, default='proficient', max_length=25)),
                ('overall_performance_score', models.FloatField(default=0.0)),
                ('ai_evidence', models.TextField(blank=True, default='')),
                ('glow', models.TextField(blank=True, default='')),
                ('grow', models.TextField(blank=True, default='')),
                ('domain_scores', models.JSONField(blank=True, default=dict)),
                ('observation_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='observations.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
