# Generated by Django 6.0.3 on 2026-04-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='ai_evidence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='dimensions_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='observation',
            name='glow',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='grow',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='instruction_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='observation',
            name='learning_env_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='observation',
            name='planning_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='observation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='observation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='overall_performance_score',
            field=models.FloatField(default=0.0),
        ),
    ]
