# Generated by Django 6.0.3 on 2026-04-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(max_length=100),
        ),
    ]
