# Generated by Django 6.0.3 on 2026-04-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_observation_ai_evidence_observation_dimensions_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='instruction_score',
            new_name='assessment_score',
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='learning_env_score',
            new_name='classroom_proc_score',
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='planning_score',
            new_name='comm_students_score',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='ai_evidence',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='grade_level',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.AddField(
            model_name='observation',
            name='culture_learning_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='observation',
            name='engaging_students_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='observation',
            name='grade_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='observation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='observation_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='questioning_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='observation',
            name='respect_env_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='observation',
            name='student_behavior_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='observation',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='rating',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='raw_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(help_text='Academic department.', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(help_text='Full name of the teacher.', max_length=150),
        ),
    ]
