# Generated by Django 6.0.3 on 2026-05-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0003_rename_instruction_score_observation_assessment_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='assessment_score',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='classroom_proc_score',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='comm_students_score',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='culture_learning_score',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='engaging_students_score',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='questioning_score',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='respect_env_score',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='student_behavior_score',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='teacher',
        ),
        migrations.AddField(
            model_name='observation',
            name='domain_2_selected',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='domain_3_selected',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='teacher_name',
            field=models.CharField(blank=True, help_text='Selected teacher name from dropdown', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='raw_notes',
            field=models.TextField(blank=True, help_text='Text written inside Observation Notes box', null=True),
        ),
    ]
